image: node:16.18.1

cache:
  paths:
    - node_modules/

stages:
  - deploy_staging
  - deploy_production

Staging:
  image: ruby:latest
  stage: deploy_staging
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - gem install faraday -v 1.8.0
    - dpl --provider=heroku --app=getgreenlit-server-dev --api-key=33c5c517-5e5a-41bb-a45e-9e87351fe037
  only:
    - staging

Production:
  image: ruby:latest
  stage: deploy_production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - gem install faraday -v 1.8.0
    - dpl --provider=heroku --app=getgreenlit-server-prod --api-key=33c5c517-5e5a-41bb-a45e-9e87351fe037
  only:
    - main
